image: node:18

definitions:
  steps:
    - step: &build-test
        name: Build and Test
        script:
          - yarn install
          - yarn build

pipelines:
  default:
    - step: *build-test

  branches:
    master:
      - step: *build-test
      - step:
          name: Deploy to Production
          deployment: production  # Esta é a chave de deployment
          script:
            - tar -czf build.tar.gz ./build
            - pipe: atlassian/scp-deploy:1.0.4
              variables:
                USER: '$SSH_USER'
                SERVER: '$SSH_HOST'
                REMOTE_PATH: '$DEPLOY_DIRECTORY'
                LOCAL_PATH: 'build.tar.gz'
                DEBUG: 'true'
                EXTRA_ARGS: '-i $BITBUCKET_PIPE_SSH_PRIVATE_KEY_PATH'
            - pipe: atlassian/ssh-run:0.2.8
              variables:
                SSH_USER: '$SSH_USER'
                SERVER: '$SSH_HOST'
                COMMAND: 'rm -rf $DEPLOY_DIRECTORY/previous_build; mv $DEPLOY_DIRECTORY/current_build $DEPLOY_DIRECTORY/previous_build; mkdir $DEPLOY_DIRECTORY/current_build; tar -xzf $DEPLOY_DIRECTORY/build.tar.gz -C $DEPLOY_DIRECTORY/current_build; cd $DEPLOY_DIRECTORY/current_build; pm2 stop all; pm2 start'
                SSH_KEY: '$BITBUCKET_PIPE_SSH_PRIVATE_KEY'
